language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - python -m nltk.downloader punkt
  - python -m nltk.downloader stopwords

script:
  - pytest tests -v -m "not longtest"
